{% set name = "nest" %}
{% set version = "v2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ version  }}
  git_url: https://github.com/nest/nest-simulator.git

build:
  skip: true  # [win]
  skip: true  # [osx]
  # skip: true  # [py<30]
  # osx_is_app: True

requirements:
  channels:
    - conda-forge
    - defaults
  build:
    - cmake >=3.6
    - git
    - llvm-openmp
    - make
    - sed
    # - gcc
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - clang
    # - clang_osx-64
    # - clangxx
    # - clangxx_osx-64
    # - llvm
    # - llvm-lto-tapi
    # -  llvm-openmp
  host:
    - ca-certificates
    - compiler-rt
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    # - libcxx
    # - libcxxabi
    - libedit
    - libffi
    - libssh2
    - libuv
    - libtool
    - llvm-openmp
    - matplotlib
    - mpi4py
    - libiconv
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - openssl
    - perl
    - python =3.7
    - rhash
    - readline
    - scipy
    - tk
    - xz
    - openssh
    - statsmodels
    - zlib
  run:
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    # - llvm-openmp  # [osx]
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python =3.7
    - python.app  # [osx]
    - readline
    - scipy
    - statsmodels
    - openssh
    - zlib

test:
  #imports:
  #  - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator

extra:
  recipe-maintainers:
    - steffengraber
  container:
    # openmpi needs ssh/rsh
    extended-base: true
