{% set name = "nest" %}
{% set version = "2.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/nest/nest-simulator
  git_tag: v2.20.2
  # url: https://github.com/nest/{{ name }}-simulator/archive/{{ version }}.tar.gz
  # sha256: 7295c936fbdd5486395b06f54f0d4d35d9a1b6ee50b7b844186ec2c92de641d1

build:
  osx_is_app: True
  skip: true  # [win or py<38 or python_impl == 'pypy']

extra:
  channels:
    - conda-forge

channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge

requirements:
  build:
    - gcc_impl_linux-64 
    - gcc_linux-64
    - gxx_impl_linux-64 
    - gxx_linux-64 
    - libgcc-ng 
    - libstdcxx-ng
    - cmake >=3.12
  host:
    - python==3.10
    - pip
    - binutils_impl_linux-64 
    - binutils_linux-64
    - cython
    - openmpi
    - boost >=1.69
    - gsl >=1.11
    - libtool
    - readline
    - numpy
  run:
    - boost
    - cython
    - gsl
    - libtool
    - matplotlib-base
    - mpi4py
    - python==3.10
    - python.app  # [osx]
    - readline
    - scipy
    - statsmodels
    - numpy
test:
  imports:
    - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator
