{% set name = "nest" %}
{% set version = "master" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ version  }}
  git_url: https://github.com/steffengraber/nest-simulator.git

build:
  number: 0
  skip: true  # [win]
  # skip: true  # [osx]
  # skip: true  # [py<30]
  osx_is_app: True

requirements:
  channels:
    - conda-forge
    - anaconda
    - defaults
  build:
    - cmake >=3.6
    - git
    - make
    - sed
    # - {{ compiler('c') }}
    # - {{ compiler('cxx') }}
  host:
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python =3.7
    - readline
    - scipy
    - openssh
    - statsmodels
    - zlib
  run:
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    - llvm-openmp  # [osx]
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python =3.7
    - python.app  # [osx]
    - readline
    - scipy
    - statsmodels
    - openssh
    - zlib

test:
  imports:
    - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator

extra:
  recipe-maintainers:
    - steffengraber
