{% set name = "nest" %}
{% set version = "v2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nest/{{ name }}-simulator/archive/{{ version }}.tar.gz
  sha256: 7295c936fbdd5486395b06f54f0d4d35d9a1b6ee50b7b844186ec2c92de641d1

build:
  osx_is_app: True
  skip: true  # [win or py<30]

extra:
  channels:
    - conda-forge

requirements:
  build:
    - cmake >=3.6
    - git
    - sed
    - llvm-openmp  # [osx]
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - gsl
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python
    - readline
    - scipy
    - openssh
    - statsmodels
    - zlib
    - libtool
  run:
    - cython
    - gsl
    - libtool
    - matplotlib
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - python
    - python.app # [osx]
    - readline
    - scipy
    - statsmodels
    - openssh
    - zlib
    - pip:
       - nestml
#test:
#  imports:
#    - nest
#  commands:
#    - nest --help
#    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator
