{% set name = "nest" %}
{% set version = "nest3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/nest/nest-simulator
  git_tag: v3.0
  # url: https://github.com/nest/{{ name }}-simulator/archive/{{ version }}.tar.gz
  # sha256: 7295c936fbdd5486395b06f54f0d4d35d9a1b6ee50b7b844186ec2c92de641d1

build:
  osx_is_app: True
  skip: true  # [win or py<38 or python_impl == 'pypy']

extra:
  channels:
    - conda-forge

requirements:
  build:
    - conda-forge::gcc_impl_linux-64 
    - conda-forge::gcc_linux-64
    - conda-forge::gxx_impl_linux-64 
    - conda-forge::gxx_linux-64 
    - conda-forge::libgcc-ng 
    - conda-forge::libstdcxx-ng
    - conda-forge::cmake >=3.12
  host:
    - conda-forge::python >=3.8
    - conda-forge::pip
    - conda-forge::binutils_impl_linux-64 
    - conda-forge::binutils_linux-64 	
    - conda-forge::cython
    - conda-forge::openmpi
    - conda-forge::boost >=1.69
    - conda-forge::gsl >=1.11
    - conda-forge::libtool
    - conda-forge::readline
  run:
    - boost
    - cython
    - gsl
    - {{ pin_compatible('libcblas') }}
    - libtool
    - llvm-openmp  # [osx]
    - matplotlib-base
    - {{ pin_compatible('ncurses') }}
    - {{ pin_compatible('numpy') }}
    - mpi4py
    - openmp  # [linux]
    - python
    - python.app  # [osx]
    - readline
    - scipy
    - statsmodels
    - openssh
    - zlib
test:
  imports:
    - nest
  commands:
    - nest --help
    - sli --help

about:
  home: http://www.nest-simulator.org/
  license:  GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: |
    NEST is a simulator for spiking neural network models that
    focuses on the dynamics, size and structure of neural systems rather than
    on the exact morphology of individual neurons.

  doc_url: https://nest-simulator.readthedocs.io/en/latest/
  dev_url: https://github.com/nest/nest-simulator
