language: ruby

services:
  - docker

before_install:
  - docker build -t nest/conda ./nest
  - docker run --name mini -it -d -e c_token=$co_token -e c_user=$co_user nest/conda
  - docker ps -a
  - docker images

script:
  - echo $?

deploy:
  provider: script
  script: docker exec -it mini bash /opt/conda-nest/anaconda_push.sh
  on:
    branch: v2.16.0
