language: python

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - wget
      - bzip2
      - g++-8
      - clang
      - llvm
      - llvm-dev

matrix:
  include:
    #- os: linux
    #  name: "NEST simulator with Python 3.7 on Xenial Linux"
    #  dist: xenial
    #  python: 3.6
    - name: "NEST simulator with Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic       # 'language: python' is an error on Travis CI macOS

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  # - conda create --yes -n test
  # - source activate test
  - conda install -y -c anaconda conda-build conda-verify automake autoconf libtool wget setuptools git
  #- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then conda install -y -c anaconda gcc_linux-64 gxx_linux-64; fi
  #- if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then conda install -y -c anaconda clang_osx-64 clangxx_osx-64 llvm
  #- llvm-openmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version; brew update; brew tap brewsci/science; brew tap brewsci/bio; brew install coreutils; fi

  - conda clean -y --all
  - echo "INSTALL NOW"
  - conda build nest
  - conda install nest --use-local

install:
  - nest --help
  - sli --helpt

script:
  # - conda install --use-local nest-simulator
  - python3 ./nest/test.py

deploy:
  skip_cleanup: true
  provider: script
  # script: /bin/bash nest/anaconda_push.sh
  script: echo "DEPLOY NOW"
  on:
    branch: master
