language: python

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - wget
      - bzip2
      - build-essential
      - cmake
      - libltdl-dev
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - ipython
      - pkg-config
      - openmpi-bin
      - libopenmpi-dev
      - python-nose
      - libpcre3
      - libpcre3-dev
      - llvm-3.6-dev
      - jq
      - pep8
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-wave-dev
      - libboost-python-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - python-mpi4py

matrix:
  include:
    #- os: linux
    #  name: "NEST simulator with Python 3.7 on Xenial Linux"
    #  dist: xenial
    #  python: 3.6
    - name: "NEST simulator with Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic       # 'language: python' is an error on Travis CI macOS

before_install:
  - echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
  - echo "+         P R E P A R E   N E S T   B U I L D   E N V I R O N M E N T         +"
  - echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
  - export SOURCEDIR=$PWD
  - echo $PWD
  - ls $PWD
  - echo $PATH
  # Install Miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda config --add channels conda-forge
  - conda info -a
  - conda create --name mybuildenv
  - conda activate mybuildenv
  - conda install -y -c conda-forge conda-build conda-verify
  - echo "BEFORE INSTALL END"
  - xcrun --show-sdk-path
  - echo "INSTALL NOW"

install:
  - conda build nest
  #- conda install nest --use-local

script:
  # - conda install --use-local nest-simulator
  - python3 ./nest/test.py
