language: ruby

services:
  - docker

before_install:
  - docker build -t nest/conda .
  - docker run --name mini -it -d -v  $(pwd):/data nest/conda
  - docker ps -a
  - docker images

script:
  - echo $?
