language: python


sudo: required

addons:
  apt:
    packages:
      - wget
      - bzip2
      - cmake

matrix:
  include:
    - os: linux
      name: "NEST simulator with Python 3.6 on Xenial Linux"
      dist: xenial
      python: 3.6
      env: TOXENV=3.6
    - name: "NEST simulator wit Python 3.6 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc && CC=gcc-8 && CXX=g++-8; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install coreutils gsl open-mpi automake autoconf libtool; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade wget cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - pip install -U pip
  - pip install -U setuptools
  - pip install cython scipy matplotlib terminaltables
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - conda config --add channels conda-forge
  - conda info -a
  - conda install -y  -c defaults -c conda-forge conda-build conda-verify anaconda-client
  - conda install -y -c conda-forge python=$TOXENV
  - conda clean -y --all

install:
  - conda build ./nest

script:
  # - conda install --use-local nest-simulator
  - python3 ./nest/test.py

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./nest/anaconda_push.sh
  on:
    branch: master
