language: python

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - wget
      - bzip2
      - build-essential
      - cmake
      - libltdl-dev
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - ipython
      - pkg-config
      - openmpi-bin
      - libopenmpi-dev
      - python-nose
      - libpcre3
      - libpcre3-dev
      - llvm-3.6-dev
      - jq
      - pep8
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-wave-dev
      - libboost-python-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - python-mpi4py

matrix:
  include:
    #- os: linux
    #  name: "NEST simulator with Python 3.7 on Xenial Linux"
    #  dist: xenial
    #  python: 3.6
    - name: "NEST simulator with Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic       # 'language: python' is an error on Travis CI macOS

before_install:
  - echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
  - echo "+         P R E P A R E   N E S T   B U I L D   E N V I R O N M E N T         +"
  - echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
  - export SOURCEDIR=$PWD
  - echo $PWD
  - ls $PWD
  - echo $PATH
  # Install Miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - conda install -y -c conda-forge conda-build conda-verify
  # - conda create --yes -n test
  # - source activate test
#  - conda install -y -c anaconda conda-build conda-verify automake autoconf libtool wget setuptools git
#  # - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then conda install -y -c anaconda gcc_linux-64 gxx_linux-64; fi
#  # - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then conda install -y -c anaconda clang_osx-64 clangxx_osx-64 llvm
#  # - llvm-openmp; fi
#  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version; brew update; brew tap brewsci/science; brew tap
#  # - brewsci/bio; brew install coreutils; fi
#  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version; brew install coreutils; fi
#  - conda clean -y --all
  - echo "BEFORE INSTALL END"
  - echo "BUILD NOW"
  - xcrun --show-sdk-path
  - conda build nest
  - echo "BUILD END"
  - which cython
  - cython --version
  - which python
  - python --version
  - which pip
  - which g++
  - g++ -v
  - which clang
  - clang -v
  # - pip list
  - which cmake
  - cmake --version
  - echo ${CC}
  - echo ${CXX}
  - ls -l
  - echo "INSTALL NOW"

install:
  - conda install nest --use-local

script:
  # - conda install --use-local nest-simulator
  - python3 ./nest/test.py
