language: python

dist: xenial

addons:
  apt:
    packages:
      - wget
      - bzip2
      - cmake

matrix:
  include:
    - python: 3.6
    #  env: NUMPY=1.9 SCIPY=0.15

    # - python: 3.7
    #  env: NUMPY=1.8 SCIPY=0.14

    - os: osx
      osx_image: xcode10.2


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install wget bzip2 cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphviz; fi
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - $HOME/miniconda/bin/conda update --yes conda

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - $HOME/miniconda/bin/conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - $HOME/miniconda/bin/conda config --add channels conda-forge
  - $HOME/miniconda/bin/conda info -a
  - $HOME/miniconda/bin/conda install -y conda-build conda-verify anaconda-client
  - $HOME/miniconda/bin/conda clean -y --all
  - $HOME/miniconda/bin/conda build ./nest
  - chmod +x ./nest/anaconda_push.sh



deploy:
  provider: script
  script: ./nest/anaconda_push.sh
  on:
    branch: master
