language: python

sudo: required

services:
- docker

before_install:
- docker pull continuumio/miniconda3
#- docker run -it --rm -v /.:/root continuumio/miniconda3 /bin/bash
- docker exec -it -v /.:/root continuumio/miniconda3 -c 'travis.sh > /proc/1/fd/1'

script:
- cd root
- ls -l
