language: python

sudo: required
dist: xenial

matrix:
  include:
    #- os: linux
    #  name: "NEST simulator with Python 3.7 on Xenial Linux"
    #  dist: xenial
    #  python: 3.6
    - name: "NEST simulator with Python 3.7 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: generic       # 'language: python' is an error on Travis CI macOS

install:
  # brew stuff
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl open-mpi libomp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  brew link --overwrite gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda install -y -c conda-forge conda-build conda-verify
  - conda build nest
  - conda install nest --use-local
  - xcode-select -s /Library/Developer/CommandLineTools/

script:
  - conda activate
  - python3 ./nest/test.py
