language: python


sudo: required

addons:
  apt:
    packages:
      - wget
      - bzip2
      - cmake

env:
  # Build and test package on all supported python version
  # - BUILD_TARGET=3.7
  - BUILD_TARGET=3.6


os:
  - linux
    dist: xenial
  - osx
    osx_image: xcode10.2


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install wget bzip2 cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  - conda config --add channels conda-forge
  - conda info -a
  - conda install -y  -c defaults -c conda-forge conda-build conda-verify anaconda-client
  - conda clean -y --all

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.


  - conda build ./nest



deploy:
  provider: script
  script: bash ./nest/anaconda_push.sh
  on:
    branch: master
