name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Build Build Environment
      run: |
        echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
        echo "+         P R E P A R E   N E S T   B U I L D   E N V I R O N M E N T         +"
        echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
        export SOURCEDIR=$PWD
        echo $PWD
        ls $PWD
        echo $PATH
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p "$HOME"/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        source "$HOME"/miniconda/etc/profile.d/conda.sh
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda config --add channels conda-forge
        conda info -a
        conda install -y -c conda-forge conda-build conda-verify
    - name: Install now
      run: |
        conda install nest --use-local
        nest --help
        sli --help