on:
  workflow_dispatch:
  workflow_call:
    inputs:
      commit_name:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
        
jobs:
  testbuild:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "replace"
        run: |
          ls
          cat meta.yaml
          set
