name: "test conda nest"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: RUNNER 1
        run: if [[ ${{ matrix.os }} == "macos-latest" ]]; then ls /Users/runner; fi
      - name: Prepare macos
        run: |
          if [[ ${{ matrix.os }} == "macos-latest" ]]; then
          MINICONDA_OS=MacOSX
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          rm miniconda.sh
          export PATH="$HOME/miniconda/bin:$PATH"
          echo $PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          $HOME/miniconda/bin/conda info -a
          fi;
      - name: RUNNER 2
        run: if [[ ${{ matrix.os }} == "macos-latest" ]]; then ls /Users/runner; fi
      - name: HOME
        run: ls $HOME


#    - run: conda config --set always_yes yes --set changeps1 no
#    - run: conda update -q conda
#        # Useful for debugging any issues with conda
#    - run: conda info -a
#    - run: conda config --add channels conda-forge
#    - run: conda install -y -c conda-forge conda-build conda-verify
#    - run: conda build ../../nest
#    - run: conda install nest --use-local