name: "test conda nest"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: BUILD NEST
        run: |
          if [[ ${{ matrix.os }} == "macos-latest" ]]; then
          brew install gsl open-mpi libomp
          brew link --overwrite gcc
          MINICONDA_OS=MacOSX
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
          bash miniconda.sh -u -b -p $HOME/miniconda
          rm miniconda.sh
          export PATH="$HOME/miniconda/bin:$PATH"
          echo $PATH
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          fi;
          conda info -a
          conda config --add channels conda-forge
          conda install -y -c conda-forge conda-build conda-verify
          conda build ../../nest
          conda install nest --use-local
